name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: ./java/MyJavaApp
        run: mvn clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-jar
          path: java/MyJavaApp/target/*.jar

      - name: Load .env into GitHub ENV
        run: |
          grep -v '^#' .env | xargs -d '\n' -I {} echo {} >> $GITHUB_ENV

      - name: Use it
        run: echo "$DB_USER"

